// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package team3176.robot.subsystems.superstructure;

import com.ctre.phoenix.sensors.AbsoluteSensorRange;
import com.ctre.phoenix.sensors.CANCoder;
import com.revrobotics.CANSparkMax;
import com.revrobotics.CANSparkMax.IdleMode;
import com.revrobotics.CANSparkMaxLowLevel.MotorType;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import team3176.robot.constants.Hardwaremap;
import team3176.robot.constants.SuperStructureConstants;
import team3176.robot.subsystems.superstructure.Arm.States;

/** Add your docs here. */
public class ArmIOSpark implements ArmIO {
    private CANSparkMax armController;
    private CANCoder armEncoder;
    private final PIDController m_turningPIDController;

    ArmIOSpark() {
        armController = new CANSparkMax(Hardwaremap.arm_CID, MotorType.kBrushless);
        armController.setSmartCurrentLimit(SuperStructureConstants.ARM_CURRENT_LIMIT_A);
        armEncoder = new CANCoder(Hardwaremap.armEncoder_CID);
        this.m_turningPIDController = new PIDController(SuperStructureConstants.ARM_kP, SuperStructureConstants.ARM_kI, SuperStructureConstants.ARM_kD);
        SmartDashboard.putNumber("Arm_kp", SuperStructureConstants.ARM_kP);
        SmartDashboard.putNumber("Arm_Kg", SuperStructureConstants.ARM_kg);
    }

    @Override
    public void updateInputs(ArmIOInputs inputs)
    {
        inputs.position = armEncoder.getPosition();
        inputs.appliedVolts = armController.getAppliedOutput() * armController.getBusVoltage();
        inputs.tempCelcius = armController.getMotorTemperature();
    }

    @Override
    public void setSpark(double pct)
    {
        armController.set(pct);
    }

    @Override
    public void setP(double kp)
    {
        m_turningPIDController.setP(kp);
    }

    @Override
    public void setPIDPosition(double desiredAngle, ArmIOInputs inputs)
    {
        double physicsAngle = (desiredAngle - SuperStructureConstants.ARM_CARRY_POS);
        
        //kg is the scalar representing the percent power needed to hold the arm at 90 degrees away from the robot
        double kg = SmartDashboard.getNumber("Arm_Kg", SuperStructureConstants.ARM_kg);
        // kp set as the fraction of control effort / error to cause control effort
        // for example .4 output is generated by a 40 degree error
        double kp = SmartDashboard.getNumber("Arm_kp", SuperStructureConstants.ARM_kP);
        setP(kp);
        double feedForward = kg * physicsAngle/SuperStructureConstants.ARM_HIGH_POS;
        if (inputs.position < SuperStructureConstants.ARM_MID_POS + 10){
            feedForward =0.0;
        }
        double turnOutput = m_turningPIDController.calculate(inputs.position, desiredAngle);
        turnOutput = MathUtil.clamp(turnOutput,-0.4,0.4);
        setSpark(turnOutput + feedForward);
        SmartDashboard.putNumber("Arm_Output", turnOutput + feedForward);
        SmartDashboard.putNumber("Arm Feed Forward", feedForward);
    }

    @Override
    public void setSparkPIDPosMode(){
        this.armEncoder.configAbsoluteSensorRange(AbsoluteSensorRange.Unsigned_0_to_360);
        this.armEncoder.configMagnetOffset(SuperStructureConstants.ARM_ENCODER_OFFSET);
        this.armEncoder.configSensorDirection(true,100);

        this.m_turningPIDController.setTolerance(SuperStructureConstants.ARM_TOLERANCE);
        //this.m_turningPIDController.enableContinuousInput() 
        this.m_turningPIDController.reset();
        this.m_turningPIDController.setP(SuperStructureConstants.ARM_kP);
        this.m_turningPIDController.setI(SuperStructureConstants.ARM_kI);
        this.m_turningPIDController.setD(SuperStructureConstants.ARM_kD);
        //this.m_turningPIDController.enableContinuousInput(0, 360);
        this.armController.setOpenLoopRampRate(0.5);
        
        this.armController.burnFlash();
    }

    @Override
    public void setMode(int mode) {
        if (mode == 1)
        {
            armController.setIdleMode(IdleMode.kCoast);
        }
        else if (mode == 2)
        {
            armController.setIdleMode(IdleMode.kBrake);
        }
    }
}
